set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)
set(CMAKE_ASM_COMPILER x86_64-linux-gnu-as)

set(CMAKE_C_COMPILER_LAUNCHER x86_64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER_LAUNCHER x86_64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(OPENSSL_ROOT_DIR "${CMAKE_FIND_ROOT_PATH}")
set(Boost_INCLUDE_DIR "${CMAKE_FIND_ROOT_PATH}/include")
set(YAML_CPP_INCLUDE_DIR "${CMAKE_FIND_ROOT_PATH}/include")
set(YAML_CPP_LIBRARY_DIR "${CMAKE_FIND_ROOT_PATH}/lib")